# docker/ansible/playbooks/hcloud_hosts_basic.yml
---
- name: Playbook hcloud_basic.yml label_stream_cache,renderer
  hosts: all
  become: true

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Installiere Basispakete
    apt: 
      name: "{{ item }}"
      state: latest
    loop: "{{ hosts_basic_packets }}"

  - name: Set hostname {{ inventory_hostname }}
    hostname:
      name: "{{ inventory_hostname }}"
