# docker/ansible/playbooks/hcloud_servers.yml
---
- name: Create or delete hcloud host status {{ host_status }}
  hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ hosts_prefix }}{{ '-%02x' | format(item) }}"
    server_type: "{{ hosts_server_type }}"
    image: "{{ hosts_image }}"
    location: "{{ hosts_location }}"
    enable_ipv4: true
    enable_ipv6: true
    labels: |
      {
        "{{ hosts_label }}": ""
      }
    ssh_keys:
      "{{ hosts_ssh_keys }}"
    state: "{{ host_status }}"
  register: hcloud_hosts

- name: Show created
  ansible.builtin.debug:
    var: hcloud_hosts

- name: Create a basic server network
  hcloud_server_network:
    network: "{{ hosts_private_network_name }}"
    server: "{{ hosts_prefix }}{{ '-%02x' | format(item) }}"
    state: "{{ host_status }}"
  when: host_status == "present"