# docker/ansible/playbooks/hcloud_hosts_basic.yml
---
- name: Playbook hcloud_hosts_basic.yml label_cotl
  hosts: label_cotl
  become: true

  tasks:
    - name: Update apt-get repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Installing basic packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ hosts_basic_packages }}"

    - name: Enable services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ hosts_enable_packages }}"

    - name: Set hostname {{ inventory_hostname }}
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
