# docker/ansible/playbooks/hcloud_servers.yml
---

# 
- name: Add ssh key
  hcloud_ssh_key:
    name: cotl-ansible-control-key
    public_key: "{{lookup('file', '../keep/id_ed25519.pub')}}"
    state: "{{ host_status }}"

- name: Create or delete hcloud host status {{ host_status }}
  hcloud_server:
    api_token: "{{ hcloud_token }}"
    name: "{{ hosts_prefix }}{{ '-%02x' | format(item) }}"
    server_type: "{{ hosts_server_type }}"
    image: "{{ hosts_image }}"
    location: "{{ hosts_location }}"
    labels: |
      {
        "{{ hosts_label }}": ""
      }
    ssh_keys:
      "{{ hosts_ssh_keys }}"
    state: "{{ host_status }}"
  register: hcloud_hosts

- name: Show created
  debug:
    var: hcloud_hosts
