# docker/ansible/playbooks/hcloud_hosts_update.yml
---
- name: Playbook hcloud_hosts_update.yml label_cotl
  hosts: label_cotl
  become: true

  tasks:
    - name: Update apt-get repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
      tags:
        - never
        - update

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
      tags:
        - never
        - update

    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: false
      tags:
        - never
        - reboot

    - name: Reboot the Debian or Ubuntu server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
      tags:
        - never
        - reboot
