---
- name: Playbook info.yml label_cotl
  hosts: label_cotl

  tasks:
  - name: Show some variables
    debug:
      var: "{{ item }}"
    loop:
      - playbook_dir
      - inventory_dir
      - inventory_hostname
      - group_names
      - groups

  - name: Show all variables and facts for this host
    ansible.builtin.debug:
      var: hostvars[inventory_hostname].ansible_facts.all_ipv4_addresses
      #verbosity: 2

  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
      verbosity: 2
