---
# site.yml

- name: Hcloud hosts update
  import_playbook: hcloud_hosts_update.yml
  tags: update

- name: Hcloud hosts basic install
  import_playbook: hcloud_hosts_basic.yml
  tags: basic

- name: Ntp configuration for all hosts
  import_playbook: ntp.yml
  tags: ntp
